### ISSUE TITLE
Links to changelogs in releases not working

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-web#210]
### Describe the bug

The links to changes in releases doesn't work for those not a member of the Keycloak organisation. We need to find some other way to list what's included in the release.

### Version

15.1+

**Comment by marcwrobel** [comment]
More information :
* if your are connected to GitHub it shows an empty list of issues if you are not a Keycloak project member,
* if your are not connected to GitHub it shows a 404.

Maybe something can be done with a GitHub projects (https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects). I am not familiar with this new feature but :
* it seems not limited to a single repository (issues have a "repository" field : https://docs.github.com/en/issues/trying-out-the-new-projects-experience/creating-a-project#issues-and-pull-requests),
* you can display a list of issues filtered by milestone (for example : https://github.com/orgs/keycloak/projects/3/views/1?layout=table&visibleFields=%5B%22Title%22%2C%22Status%22%2C%22Labels%22%2C%22Milestone%22%5D&filterQuery=no%3Amilestone),
* this list is visible even when not connected to GitHub.

And may be as a temporary fix you could replace `https://github.com/issues` by `https://github.com/keycloak/keycloak/issues` in [templates/blog-release.ftl](https://github.com/keycloak/keycloak-web/blob/main/templates/blog-release.ftl) ?
