### ISSUE TITLE
The title page implies that it's possible to login to the keycloak.org website

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-web#232]
### Describe the bug

The login form is pretty convincing and gives the wrong impression that it's actually possible to login while in reality it's just a picture. 
![Screenshot 2022-01-07 at 15 42 57](https://user-images.githubusercontent.com/13906855/148561556-b2288b5e-ffeb-4850-a3d9-620550e55a6e.png)

### Version

16.1.0

**Comment by edewit** [comment]
it could be improved with a border and an annotation like this: 
![image](https://user-images.githubusercontent.com/51133/148562515-cd8ea6ed-0f9a-4782-bf40-4ec5fc1c21ef.png)

**Comment by edewit** [comment]
also the new login page look more like this: 
![image](https://user-images.githubusercontent.com/51133/148562683-cec14f6d-78c2-4424-b60e-bc70618578b2.png)

**Comment by vmuzikar** [comment]
@edewit I think we should use a screenshot with the grey background and perhaps even with the logo. Pretty much what you sent above. That'd be explicit enough on its own that it's a screenshot.

**Comment by stianst** [comment]
I don't really think this is a big issue, and don't particularly like any of the suggestions. The caption is just adding additional noise, and including the background makes it bigger, and also looks quite ugly.

**Comment by vmuzikar** [comment]
How about placing the Keycloak Man there instead of the "dummy" login form? :) Isn't he kinda representation of SSO?

**Comment by stianst** [comment]
The "Keycloak Man" was the old logo, and represented Keycloak, not SSO. SSO is just a feature of Keycloak. The login page illustrates better to someone not familiar with Keycloak what it is.

**Comment by stianst** [comment]
Updated the screenshot here:
https://github.com/keycloak/keycloak-web/pull/241/files#diff-2a17560f86e6e9cac42629d90536af695a7aecb2d0900a1c192727163e80f000
