### ISSUE TITLE
Vue 3 implementation examples

### ISSUE THREAD

**Issue by Sazzels** [keycloak/keycloak-web#263]
### Description

Vue 3 will be the new standard starting 07.02.2022. 
> TL;DR: Vue 3 will become the new default version on Monday, February 7, 2022!

Source: [https://blog.vuejs.org/posts/vue-3-as-the-new-default.html](https://blog.vuejs.org/posts/vue-3-as-the-new-default.html)

Can the documentation [https://www.keycloak.org/securing-apps/vue](https://www.keycloak.org/securing-apps/vue) be updated accordingly to support the new Vue 3 syntax for adding keycloak to the project? 

### Motivation

A propper documentation how keycloak should be implemented in vue 3 projects would be highly appreciated. 
There are some projects in circulation that allow the implementation in vue 3. Unfortunately, they don't offer the support I would like for a productive operation of keycloak in my projects.

### Details

```javascript
// before - Vue 2
...
new Vue({
  el: '#app',
  render: h => h(App, { props: { keycloak: keycloak } })  // breaking
})
...
Vue.prototype.$keycloak = () => {}
```

```javascript
// after - Vue 3
const app = createApp({})
app.config.globalProperties.$keycloak = () => {} // basic global registration
```

**Comment by stianst** [comment]
A contribution would be more than welcome, but since the current Vue example is a community contribution we are not planning on updating that to Vue 3 ourselves.
