### ISSUE TITLE
Wrong links in the Docker documentation

### ISSUE THREAD

**Issue by eluchsinger** [keycloak/keycloak-web#279]
### Describe the bug

This is an issue in the documentation "Keycloak - Docker - Getting Started".

The link in the [docs](https://www.keycloak.org/getting-started/getting-started-docker#_login_to_the_admin_console) to open the admin console is `http://localhost:8080/auth/admin`, but when I go through the steps, that link goes to a page not found.

The correct link would probably be: `http://localhost:8080/admin/`

### Version

17.0.0

### Expected behavior

Clicking on the link in the Getting Started documentation opens a tab to log into the admin console.

### Actual behavior

Clicking the link in the Getting Started documentation opens a tab with a "Page not found" result.

### How to Reproduce?

1. Run the docker image using the command in the getting started section.
2. Click on the link in the documentation to open the admin console.

**Comment by paul-thompson-helix** [comment]
Likewise the link `Open the [Keycloak Account Console](http://localhost:8080/auth/realms/myrealm/account)` should be `http://localhost:8080/realms/myrealm/account

Looks like they're defined in variables `links-admin-console` & `links-account-console`

The values are in visible in raw mode: https://raw.githubusercontent.com/keycloak/keycloak-web/77b8697df8f2b1dc4e17eb642fd126ea0ec3bcc2/guides/getting-started/getting-started-docker.adoc
