### ISSUE TITLE
Change page titles so that topic is listed first

### ISSUE THREAD

**Issue by myfirstnameispaul** [keycloak/keycloak-web#282]
### Description

The current page titles are in the format:

Keycloak - Category - Article topic

Example:

```html
    <title>Keycloak - Server - Configuring Keycloak</title>
```

With many tabs open simultaneously to the various pages, the tab title is not very useful in figuring out which tab to go to:

![tabsnotreadable](https://i.imgur.com/u0K6B1f.png)

### Motivation

With the newer guides, it seems what was covered previously in a single page is now on many pages, so having many tabs open is the way to go, except I find I'm heavily using <kbd>Ctrl</kbd>+<kbd>Tab</kbd> scanning for the correct tab since the titles don't inform me of the topic in a tab.

**Comment by stianst** [comment]
Incorporated here:
https://github.com/keycloak/keycloak-web/commit/5b660f780c151daea0059f7a91b56e56baf8926a
