### ISSUE TITLE
Clean "Getting started" guides regarding the operator

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak-web#292]
### Description

Review and update or remove the "Getting started" guides for OpenShift and Kubernetes using the operator.

**Comment by vmuzikar** [comment]
@andreaTP Do you mean these two?
https://www.keycloak.org/getting-started/getting-started-operator-kubernetes
https://www.keycloak.org/getting-started/getting-started-operator-openshift

That is for the old operator. The only thing that needs to be done there is to clearly mark it's for the old operator.

**Comment by andreaTP** [comment]
Yup, this issue is only a reminder for doing it.

**Comment by stianst** [comment]
I'd say we should just mark them as for the old operator, then after the new operator is the default one we should update the guides to be for the new operator.
