### ISSUE TITLE
OpenShift Quickstart points to latest

### ISSUE THREAD

**Issue by vkareh** [keycloak/keycloak-web#298]
### Describe the bug

When following the quickstart guide for OpenShift, the contents pertain to the 'main' branch, but the sample keycloak.yaml file shows as 'latest'. Following this guide as-is leads to errors, and modifying the parameters to match lead to a CrashLoopBackOff pod. Changing the sample yaml file to use 'main' fixes it.

### Version

17.0.1

### Expected behavior

Following the guide verbatim should succeed

### Actual behavior

Following the guide verbatim leads to errors and a possible CrashLoopBackOff in the service pod

### How to Reproduce?

Follow the guide, copy-pasting the commands directly

**Comment by DGuhr** [comment]
Hi @vkareh I just spun up code ready container and c&ped the exact steps from the quickstarts guide and I could spin up my keycloak pod without going into `CrashLoopBackOff`. Could also reach welcome page, admin page and login. 

Just to make sure, we're both talking about the same guide [here](https://www.keycloak.org/getting-started/getting-started-openshift), right? 

Closing here for now as not reproducible. Feel free to add more information and we can re-open it.

**Comment by vkareh** [comment]
Yes - seems like the 'latest' sample file was updated to match the one from the 'main' branch (they had diverged when I filed this bug).

Thanks!
