### ISSUE TITLE
Keycloak test app no longer work with Keycloak 18

### ISSUE THREAD

**Issue by garronej** [keycloak/keycloak-web#306]
### Describe the bug

https://user-images.githubusercontent.com/6702424/164978897-915915e2-50b1-4a5e-8bfd-5a568c1650fb.mov

### Version

18.0.0

### Expected behavior

To see the login page

### Actual behavior

fallback to error.ftl with message `Invalid parameter: redirect_uri` 

### How to Reproduce?

https://www.keycloak.org/getting-started/getting-started-docker

The parts when creating a user can be skipped. 

### Anything else?

Best regards

**Comment by stianst** [comment]
I've just double checked the getting started guide and it's working just fine here.

This issue would be caused by the client not being configured correctly. Did you remember to add the `Root URL` for the `myclient`?

**Comment by garronej** [comment]
Thank you for your reply,  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/Screen%20Recording%202022-04-25%20at%2009.32.04.mov

I can't see what I am missing

**Comment by stianst** [comment]
Could you send a screenshot instead of video please?

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/165062475-0e39dd1c-0056-48ef-bb12-2e19f3431ed3.png)

![image](https://user-images.githubusercontent.com/6702424/165062547-9a86f238-ac64-4982-b8f0-74670731b887.png)

![image](https://user-images.githubusercontent.com/6702424/165062597-918d5a88-662a-4578-be0b-3a5b113613c6.png)

**Comment by stianst** [comment]
I see it's missing the redirect uri, which is needed. When you create a new client and specify a root url during the first step it'll prefill some other urls. However, if you add the root url after the client is created it won't.

Simplest is probably just to create the client and create a new one. Alternatively you can add a redirect uri, should he https://www.keycloak.org/app/

**Comment by garronej** [comment]
Thank you for the support I got it working 😊  

> When you create a new client and specify a root url during the first step it'll prefill some other urls. However, if you add 
> the root url after the client is created it won't.  

OK, I see.  
In v18 you there is no longer a field for specifying root_url.  
![image](https://user-images.githubusercontent.com/6702424/165069967-88fdb5ee-7963-45eb-912f-b527376108f7.png)

Thus the "Valid redirect URIs" have to be manually specified which is not specified in [the getting started guide](https://www.keycloak.org/getting-started/getting-started-docker).  

> redirect uri, should he https://www.keycloak.org/app/  

It must have a wildchar: https://www.keycloak.org/app/*

Thank for the support,  
Best regards

**Comment by stianst** [comment]
There's no Root URL in the preview new admin console, but there is in the default admin console for KC 18. It should work without the '*', but just tried that and it doesn't. So, looks like there might be an issue, probably in keycloak.js as I'm seeing a pretty weird URL in the error message

`type=LOGIN_ERROR, realmId=myrealm, clientId=myclient, userId=null, ipAddress=127.0.0.1, error=invalid_redirect_uri, redirect_uri=https://www.keycloak.org/app/#url=http://localhost:8080&realm=myrealm&client=myclient
`
