### ISSUE TITLE
Docker documentation is lacking

### ISSUE THREAD

**Issue by GiganteX** [keycloak/keycloak-web#357]
### Describe the bug

The docker documentation is lacking.

There is no information on how to create a data volume. Which directories must be included in the volume?

There is no link to the image in the Docker Hub. There are MANY other keycloak images on the Docker Hub, it's quite the adventure/risk looking for one there. There is even a "keycloak" user providing one, but I doubt that one is you. You really should make sure that your official image is the top search result on the Docker Hub.

### Version

current

**Comment by stianst** [comment]
Can you open an issue in https://github.com/keycloak/keycloak/issues as that's where the guides live, this is just used to publish them. Please make the subject a bit more specific than "... is lacking", perhaps two separate issues, one for the mounts and another for the lack of image names.
