### ISSUE TITLE
demo app at https://www.keycloak.org/app/ is broken

### ISSUE THREAD

**Issue by thetilliwilli** [keycloak/keycloak-web#389]
### Describe the bug

When trying to press Save button JS error occurs.

![image](https://user-images.githubusercontent.com/25109940/233804967-f44bc530-9d34-4996-96ff-932086b23a5d.png)

### Version

21.1.0

### Expected behavior

Save button works

### Actual behavior

nothing happens after Save button have pressed

### How to Reproduce?

1. goto https://www.keycloak.org/app/
2. press Save button

### Anything else?

it looks like app.js use invalid continuation function 

instead of 

```javascript
keycloak.init({
            checkLoginIframe: false
        }).success
``` 

it should be 
```javascript
keycloak.init({
            checkLoginIframe: false
        }).then
```
![image](https://user-images.githubusercontent.com/25109940/233805199-c4c44bf7-562c-436a-9a4c-56b6f9f4b51b.png)

**Comment by stianst** [comment]
This has already been resolved
