### ISSUE TITLE
Link to Keycloak 18 Administration REST API is broken

### ISSUE THREAD

**Issue by canon-aris-van-dijk** [keycloak/keycloak-web#408]
### Describe the bug

The documentation page of Keycloak 18 (https://www.keycloak.org/archive/documentation-18.0.html) refers to [Administration REST API](https://www.keycloak.org/docs-api/18.0.2/rest-api/index.html) which is a broken link.

### Version

18

### Expected behavior

The link "Administration REST API" on https://www.keycloak.org/archive/documentation-18.0.html should point to an existing web page.

### Actual behavior

The web page returns 404.

### How to Reproduce?

- Go to https://www.keycloak.org/
- Click Docs
- Click "For previous releases go here"
- Click 18.0
- Click "Administration REST API"

**Comment by stianst** [comment]
We no longer list Keycloak 18 on the website, for older versions you can still retrieve the artifacts from https://github.com/keycloak/keycloak/releases
