### ISSUE TITLE
Keycloak client documentation not re-published on web page during keycloak-client release

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-web#524]
It looks that Keycloak client documentation is not re-published during the keycloak-client release. 

For example there was this documentation change: https://github.com/keycloak/keycloak-client/commit/7ba900d3a45e83a0a40e197fb8bebbe29df96e47 , which is available in Keycloak-client 26.0.1 release, which was already released. But it is not published on latest web page as of today: https://www.keycloak.org/securing-apps/authz-client . 

However it is correctly published on the "nightly build" of keycloak guides: https://www.keycloak.org/nightly/securing-apps/authz-client

**Comment by rmartinc** [comment]
Already done by https://github.com/keycloak/keycloak-web/commit/ea2932057bcb6e4bc28947c6f85ae43275455e44.
