### ISSUE TITLE
Add Apache V2 License file

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-web#534]
### Description

Add Apache V2 license file.

### Motivation

To ease contributions from a broader audience we should add a proper license file as we have for other keycloak repositories.

**Comment by ahus1** [comment]
+1 for thiat. Ple

**Comment by ahus1** [comment]
+1 for that. Please go a head an create a PR. 

(Sorry, I mis-clicked and accidentally closed it. It is now open again).
